### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by kenorb** [alexmcmorris/tab-dupectomy#6]
When installing plugin from the [webstore page](https://chrome.google.com/webstore/detail/tab-dupectomy/nkkedbpcfdogedipgdhgeknjdphaplbk), the error reads:

> Invalid manifest

Google Chrome Version 67.0.3396.0 (Official Build) Canary (64-bit)

**Comment by Kylis** [comment]
[nkkedbpcfdogedipgdhgeknjdphaplbk.zip](https://github.com/alexmcmorris/tab-dupectomy/files/2087145/nkkedbpcfdogedipgdhgeknjdphaplbk.zip)

unzip this and then follow these instructions to load an unpacked extension 
https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

Should work again after that.

**Comment by kenorb** [comment]
Thanks, it loads fine, however, there is an error:

> Unrecognized manifest key 'background_page'.

Line:   

    "background_page": "background.html",
 
Tested in: Chrome Version 69.0.3451.0 (Official Build) Canary (64-bit) on macOS

Could you also send the PR?

**Comment by Kylis** [comment]
I couldn't get it to work. It just loaded up a button for it.
In the meantime I just sucked it up and switched to https://chrome.google.com/webstore/detail/duplicate-tabs-closer/gnmdbogfankgjepgglmmfmbnimcmcjle

**Comment by rjmunro** [comment]
I use this extension all the time, but it seems to have disappeared from my chrome installation in the last couple of days, and if I try to reinstall it from here: https://chrome.google.com/webstore/detail/tab-dupectomy/nkkedbpcfdogedipgdhgeknjdphaplbk/reviews I get the error mentioned above.

It would be a shame to loose this extension - it's really useful, and the code is short enough to review in just a few minutes.
