### ISSUE TITLE
countDuplicateSiblings being called multiple times

### ISSUE THREAD

**Issue by dryack** [alexmcmorris/tab-dupectomy#8]
I abuse the hell out of my browser, and noted that there were pauses every time I created or updated a tab.     
(I discovered eventually that I was having fairly large major GCs during those pauses.)

I added `console.log(tab)`  to countDuplicateSiblings, and saw

![2019-04-02 13_51_41-DevTools(1)](https://user-images.githubusercontent.com/4473431/55435520-e3d97480-554e-11e9-847a-3c2441dc3fd8.png)

Upon researching it is happening because chrome.tabs.onUpdated will fire for _any_ type of tab update.  A favicon loading, an iframe, etc.

**Comment by alexmcmorris** [comment]
I would suggest using null object pattern
